/**
 * Vuex Mutation Types
 */
const WRITE_NAME = "WRITE_NAME";
const WRITE_POSTALCODE = "WRITE_POSTALCODE";
const SELECT_PREFECTURE = "SELECT_PREFECTURE";
const WRITE_CITYSTREET = "WRITE_CITYSTREET";
const REGIST_DESTINATION = "REGIST_DESTINATION";

export default {
  WRITE_NAME,
  WRITE_POSTALCODE,
  SELECT_PREFECTURE,
  WRITE_CITYSTREET,
  REGIST_DESTINATION
};
