/**
 * Redux Action Types
 */
export enum ACTION_TYPES {
  WRITE_NAME = "WRITE_NAME",
  WRITE_POSTALCODE = "WRITE_POSTALCODE",
  SELECT_PREFECTURE = "SELECT_PREFECTURE",
  WRITE_CITYSTREET = "WRITE_CITYSTREET",
  REGIST_DESTINATION = "REGIST_DESTINATION"
}
